elasticsearch:
  port: 9200
  host: 'http://127.0.0.1'
  indices:
    repos: 'gh_repos'
    issues: 'gh_issues_'
    projects: 'gh_projects_'
    labels: 'gh_labels_'
    milestones: 'gh_milestones_'
    prs: 'gh_prs_'
fetch:
  max_nodes: 30
github:
  username: 'YOUR_USERNAME'
  token: 'TOKEN_HERE'
